image: Ubuntu

build_script:
  - ps: Invoke-WebRequest 'https://dot.net/v1/dotnet-install.sh' -OutFile dotnet-install.sh;  $installDir =  $env:PATH.Split([System.IO.Path]::PathSeparator) | Select-Object -First 1; Write-Verbose "inst $installDir" -Verbose; bash dotnet-install.sh --version $dotNetCoreSDKVersion --install-dir "'$installDir'"
  - ps: $PSVersionTable; dotnet --version